[package]
name = "bibi"
description = "A simple Hololive Schedule CLI tool."
version = "0.1.0"
authors = ["Myuwi <myuwi@pm.me>"]
license = "MIT"
edition = "2021"

[dependencies]
chrono = "0.4.19"
clap = { version = "3.1.6", features = ["derive"] }
html-escape = "0.2.9"
owo-colors = "3.2.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
unicode-width = "0.1.7"
